import os
#10 NUMEROS
num = [34,25,35,86,85,46,59,68,76,1]
print("\nLista dos 10 números\n")
for N in num:
    print(N)

#5 NOMES
nomes = ["André", "Enzo", "Juliano", "Murilo", "Nathan"]
print("\nLista dos nomes\n")
for N in nomes:
    print(N)

#3 FRUTAS
frutas = ["Abacate", "Morango", "Amora"]
print("\nLIsta de frutas\n")
for N in frutas:
    print(N)

#CHAMADA
chamada = ["1-ALEXANDRE BAGINI", "2-ALEXANDRE LEMES FERREIRA DA SILVA", "3-ANA CAROLINE MORAES MALHEIRO", "4-ANA JÚLIA FELISBERTO BUENO", "5-ANDRÉ FELIPE ROSA DA SILVA", "6-ARTHUR MATHEUS DE MOURA", "7-CESAR AUGUSTO CAVALLARO", "8-DIEGO DA ROZ OTAVIANO", "9-ENZO BIASON MANHA", "10-GABRIEL SOARES NECO", "11-GIULIA DA CUNHA ROCHA", "12-GUILHERME AUGUSTO DOS SANTOS SILVA", "13-GUILHERME SOUZA LIMA", "14-ISABELLE DANIEL DOS ANJOS", "15-JOÃO PEDRO PORTOCARRERO COQUELLETTI","16-JÚLIA MONTEIRO DALLA VECCHIA", "17-JULIANO SILVESTRE DIOGO", "18-KAUÊ LIMA BARBOSA", "19-LEONARDO RODRIGO CAETANO GALVÃO", "20-LETÍCIA RODRIGUES DE PAIVA", "21-MARIA EDUARDA DOS SANTOS NASCIMENTO", "22-MIRELLA TURQUETI CORREA GONÇALVES", "23-MURILO AUGUSTO CARNEIRO", "24-NATÁLIA PAZ DA SILVA", "25-NATALIA VAZ CERQUEIRA", "26-NATHAN HENRIQUE DA CUNHA SOUZA", "27-PABLO DA SILVA FERREIRA DE LIMA", "28-RAFAELA FATIMA DE SOUZA ALVES", "29-RUAN HENRIQUE PALMEIRA", "30-THAINÁ CRISTINA DE SOUZA", "31-VINICIUS DE OLIVEIRA MOURA", "32-VINICIUS FANTINELLI PIRES BARBOSA", "33-VÍTOR VINÍCIUS GONÇALVES", "34-YURI AZEVEDO ANTUNES DE SOUZA"]
print("\nChamada da sala\n")

for N in chamada:
    print(N)

os.system("pause")

